language: ruby
rvm:
  - 2.6
cache: bundler

script:
  - bundle
  - JEKYLL_ENV=production bundle exec jekyll build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: false
  local-dir: _site
  repo: Nondv/weird-programming.dev
  target-branch: gh-pages
  on:
    branch: master
