name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        -e JEKYLL_ENV=production \
        jekyll/minimal:4.0 \
        /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.4.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-actions-test
        FOLDER: ${{ github.workspace }}/_site # The folder the action should deploy.

