name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JEKYLL_ENV: production
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/cache@v1
      with:
        path: .bundler
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path .bundler
        bundle install --jobs 4 --retry 3
    - name: Build
      run: bundle exec jekyll build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.4.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-actions-test
        FOLDER: _site

