name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - uses: actions/cache@v1
      with:
        path: .bundler
        key: bundler-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-${{ runner.os }}-
    - name: Bundle install
      run: |
        gem install bundler:2.0.2
        bundle config path .bundler
        bundle install --jobs 4 --retry 3
    - name: Build
      run: bundle exec jekyll build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
